version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "${SERVER_PORT:-8080}:8080"
    environment:
      - PROFILE=${PROFILE:-dev}
      - DATASOURCE_URL=${DATASOURCE_URL:-jdbc:postgresql://postgres:5432/agenda}
      - DATASOURCE_USERNAME=${DATASOURCE_USERNAME:-admin}
      - DATASOURCE_PASSWORD=${DATASOURCE_PASSWORD:-admin}
      - REDIS_HOST=${REDIS_HOST:-redis}
      - REDIS_PORT=${REDIS_PORT:-6379}
      - REDIS_PASSWORD=${REDIS_PASSWORD:-admin}
      - EMAIL_HOST=${EMAIL_HOST:-smtp.gmail.com}
      - EMAIL_PORT=${EMAIL_PORT:-587}
      - EMAIL_USERNAME=${EMAIL_USERNAME}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - API_BASE_URL=${API_BASE_URL:-http://localhost:8080/api/v1}
      - FRONTEND_BASE_URL=${FRONTEND_BASE_URL:-http://localhost:3000}
    networks:
      - app-network
    depends_on:
      - postgres
      - redis

  redis:
    image: redis:7.4.1
    container_name: redis
    ports:
      - "${REDIS_PORT:-6379}:6379"
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD:-admin}
    networks:
      - app-network

  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-admin}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-admin}
      - POSTGRES_DB=${POSTGRES_DB:-agenda}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
